stages:
  - module-pipeline
  - deploy
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

frontend:
  stage: module-pipeline
  trigger: 
    include: frontend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipeline
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - backend/**/*

# deploy-staging:
#   stage: deploy
#   variables:
#     GIT_STRATEGY: none
#     DOCKER_HOST: ssh://${DEV_USER}@${DEV_HOST}
#   cache: []
#   image: docker:20.10.12-dind
#   environment:
#     name: momo-store-staging
#     deployment_tier: staging
#     url: ${FQDN}
#   before_script:
#     - apk add openssh-client bash
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#     # Устанавливаем docker-compose
#     - >
#       wget -O docker-compose https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64
#     - chmod +x ./docker-compose
#     - > #Скачиваем docker-compose.yml 
#       wget -O docker-compose.yml --header "PRIVATE-TOKEN: ${MY_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/files/docker-compose.yml/raw?ref=${CI_COMMIT_SHA}"

#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - >
#       docker context create remote --docker "host=ssh://${DEV_USER}@${DEV_HOST}"
#     - ./docker-compose --context remote pull
#     - ./docker-compose --context remote up -d --force-recreate

# deploy-production:
#   stage: deploy
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       when: manual
#   environment:
#     name: momo-store-prod
#     deployment_tier: production
#     url: ${PRODUCTION_URL}
#   extends: deploy-staging

.trigger-infra:
  trigger:
    project: a.cherkashin/momo-infrastructure
    branch: $CI_COMMIT_REF_NAME
    strategy: depend

.helm_prepare:
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p ~/.kube
    - base64 -d ${KUBECONFIG_ENCRYPTED} > ~/.kube/config
    - chmod 0600 ~/.kube/config
    - helm repo add momo-store --username ${NEXUS_USER} --password ${NEXUS_PASS} $NEXUS_REPO_URL
    - helm repo update

deploy-staging:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
  environment:
    name: momo-store-staging
    deployment_tier: staging
    url: ${STAGING_URL}
    on_stop: delete-app
  extends: .helm_prepare
  script:
    - >
      helm upgrade --install --atomic
      --kubeconfig ~/.kube/config
      --set frontend.fqdn=${STAGING_FQDN}
      --namespace momo-staging --create-namespace
      momo-store-staging momo-store/momo-store

delete-app:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
      when: manual
  environment:
    name: momo-store-staging
    deployment_tier: staging
    url: ${STAGING_URL}
    action: stop
  extends: .helm_prepare
  script:
    - helm uninstall --kubeconfig ~/.kube/config --namespace momo-staging momo-store-staging
    - kubectl delete namespace momo-staging

deploy-production:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      when: manual
  extends: .trigger-infra

create-env-prod:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  environment:
    name: momo-store
    deployment_tier: production
    url: ${PRODUCTION_URL}
  needs:
    - deploy-production
  script:
    - echo Deploy production
  