stages:
  - module-pipeline
  - deploy
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

frontend:
  stage: module-pipeline
  trigger: 
    include: frontend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipeline
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - backend/**/*

.trigger-infra:
  trigger:
    project: a.cherkashin/momo-infrastructure
    branch: $CI_COMMIT_REF_NAME
    strategy: depend

.helm_prepare:
  image: dtzar/helm-kubectl
  before_script:
    - mkdir -p ~/.kube
    - base64 -d ${KUBECONFIG_ENCRYPTED} > ~/.kube/config
    - chmod 0600 ~/.kube/config
    - helm repo add momo-store --username ${NEXUS_USER} --password ${NEXUS_PASS} $NEXUS_REPO_URL
    - helm repo update

deploy-staging:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
  environment:
    name: momo-store-staging
    deployment_tier: staging
    url: ${STAGING_URL}
    on_stop: delete-app
  extends: .helm_prepare
  script:
    - >
      helm upgrade --install --atomic
      --kubeconfig ~/.kube/config
      --set frontend.fqdn=${STAGING_FQDN}
      --namespace momo-staging --create-namespace
      momo-store-staging momo-store/momo-store

delete-app:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH'
      when: manual
  environment:
    name: momo-store-staging
    deployment_tier: staging
    url: ${STAGING_URL}
    action: stop
  extends: .helm_prepare
  script:
    - helm uninstall --kubeconfig ~/.kube/config --namespace momo-staging momo-store-staging
    - kubectl delete namespace momo-staging

deploy-production:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
      when: manual
  extends: .trigger-infra

create-env-prod:
  stage: deploy
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH'
  environment:
    name: momo-store
    deployment_tier: production
    url: ${PRODUCTION_URL}
  needs:
    - deploy-production
  script:
    - echo Deploy production
  