stages:
  - module-pipeline
  - deploy
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

frontend:
  stage: module-pipeline
  trigger: 
    include: frontend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - frontend/**/*

backend:
  stage: module-pipeline
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend
  only:
    changes:
      - backend/**/*

# deploy-staging:
#   stage: deploy
#   variables:
#     GIT_STRATEGY: none
#     DOCKER_HOST: ssh://${DEV_USER}@${DEV_HOST}
#   cache: []
#   image: docker:20.10.12-dind
#   environment:
#     name: momo-store-staging
#     deployment_tier: staging
#     url: ${FQDN}
#   before_script:
#     - apk add openssh-client bash
#     - eval $(ssh-agent -s)
#     - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
#     - mkdir -p ~/.ssh
#     - chmod 700 ~/.ssh
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 644 ~/.ssh/known_hosts
#     # Устанавливаем docker-compose
#     - >
#       wget -O docker-compose https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64
#     - chmod +x ./docker-compose
#     - > #Скачиваем docker-compose.yml 
#       wget -O docker-compose.yml --header "PRIVATE-TOKEN: ${MY_TOKEN}" "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/repository/files/docker-compose.yml/raw?ref=${CI_COMMIT_SHA}"

#   script:
#     - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
#     - >
#       docker context create remote --docker "host=ssh://${DEV_USER}@${DEV_HOST}"
#     - ./docker-compose --context remote pull
#     - ./docker-compose --context remote up -d --force-recreate

# deploy-production:
#   stage: deploy
#   rules:
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
#       when: manual
#   environment:
#     name: momo-store-prod
#     deployment_tier: production
#     url: ${PRODUCTION_URL}
#   extends: deploy-staging

deploy-chart:
  stage: deploy
  when: manual
  variables:
    APP_VERSION: $VERSION
  trigger: 
    project: a.cherkashin/momo-infrastructure
    strategy: depend

create-env:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  environment:
    name: momo-store
    deployment_tier: production
    url: ${FQDN}
  needs:
    - deploy-chart
  script:
    - echo Deploy
  