version: '3.4'

services:

  frontend:
    image: ${CI_REGISTRY_IMAGE}/momo-frontend:latest
    restart: always
    hostname: frontend
    environment:
      - API_URL=http://yapvm.cherkashin.org/api
    ports:
      - 80:8080
    networks:
      - momo-network

  backend:
    image: ${CI_REGISTRY_IMAGE}/momo-backend:latest
    restart: always
    hostname: backend
    networks:
      - momo-network

networks:
  momo-network:
      driver: bridge
